rdevelopment/rdevelopment/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(('workshops.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('accounts/', include('allauth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rdevelopment/users/urls.py
from django.urls import path

# View
from users import views


urlpatterns = [

    # Management
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route='me/profile/',
        view=views.UpdateProfileView.as_view(),
        name='update'
    ),

    # Posts
    path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    )

]

rdevelopment/workshops/urls.py
# Django
from django.urls import path

# Views
from workshops import views

urlpatterns = [

    path(
        route='',
        view=views.PostsFeedView.as_view(),
        name='feed'
    ),

    path(
        route='posts/new/',
        view=views.CreatePostView.as_view(),
        name='create'
    ),

    path(
        route='posts/<int:pk>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),


    path(
        route='search/',
        view=views.PostsSearchView.as_view(),
        name='search',

    )
]

rdevelopment/users/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db import models
from django.dispatch import receiver


class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)

    picture = models.ImageField(
        upload_to='users/pictures',
        blank=True,
        null=True
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

rdevelopment/workshops/models.py
from django.db import models
from django.contrib.auth.models import User


class Workshop(models.Model):
    """Post model."""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey('users.Profile', on_delete=models.CASCADE)

    title = models.CharField(max_length=255,default='N/A')
    description = models.CharField(max_length=255,default='N/A')

    txt = models.TextField()

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)


    def __str__(self):
        """Return title and username."""
        return '{} by @{}'.format(self.title, self.user.username)

rdevelopment/users/forms.py
# Django
from django import forms

# Models
from django.contrib.auth.models import User
from users.models import Profile


class SignupForm(forms.Form):
    """Sign up form."""

    username = forms.CharField(min_length=4, max_length=50)

    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )

    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)

    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )

    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')

        return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

rdevelopment/workshops/forms.py
"""Post forms."""

# Django
from django import forms

# Models
from workshops.models import Workshop




class PostForm(forms.ModelForm):
    """Post model form."""

    class Meta:
        """Form settings."""

        model = Workshop
        fields = ('user', 'profile', 'title','description', 'txt')

rdevelopment/users/views.py
# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, FormView, UpdateView

# Models
from django.contrib.auth.models import User
from workshops.models import Workshop
from users.models import Profile

# Forms
from users.forms import SignupForm


class UserDetailView(LoginRequiredMixin, DetailView):
    """User detail view."""

    template_name = 'users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """Add user's posts to context."""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Workshop.objects.filter(user=user).order_by('-created')
        return context


class SignupView(FormView):
    """Users sign up view."""

    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    """Update profile view."""

    template_name = 'users/update_profile.html'
    model = Profile
    fields = ['website', 'biography', 'phone_number', 'picture']

    def get_object(self):
        """Return user's profile."""
        return self.request.user.profile

    def get_success_url(self):
        """Return to user's profile."""
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username': username})


class LoginView(auth_views.LoginView):
    """Login view."""

    template_name = 'users/login.html'


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """Logout view."""

    template_name = 'users/logged_out.html'

rdevelopment/workshops/views.py
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, ListView
from django.shortcuts import render

# Forms
from workshops.forms import PostForm

# Models
from workshops.models import Workshop

class PostsFeedView(LoginRequiredMixin, ListView):
    """Return all published posts."""
    template_name = 'posts/feed.html'
    model = Workshop
    ordering = ('created',)
    paginate_by = 30
    context_object_name = 'posts'

class PostsSearchView(LoginRequiredMixin, ListView):
    """Return all published posts."""
    template_name = 'posts/search.html'
    model = Workshop
    ordering = ('-created',)
    paginate_by = 30
    context_object_name = 'posts'

class PostDetailView(LoginRequiredMixin, DetailView):
    """Return post detail."""

    template_name = 'posts/detail.html'
    queryset = Workshop.objects.all()
    context_object_name = 'post'


class CreatePostView(LoginRequiredMixin, CreateView):
    """Create a new post."""

    template_name = 'posts/new.html'
    form_class = PostForm
    success_url = reverse_lazy('posts:feed')

    def get_context_data(self, **kwargs):
        """Add user and profile to context."""
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['profile'] = self.request.user.profile
        return context

rdevelopment/templates/_nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url "posts:feed" %}">
            <img src="{% static "img/singer.png" %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">


                <li class="nav-item">
                    <a href="{% url "users:detail" request.user.username %}">
                        {% if request.user.profile.picture %}
                            <img src="{{ request.user.profile.picture.url }}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% else%}
                            <img src="{% static 'img/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% endif %}
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url "posts:create" %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                        <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
                  </li>
                <li class="nav-item nav-icon">
                  <a href="{% url "posts:search" %}">
                        <i class="fas fa-search"></i>
                  </a>
                </li>
                <li class="nav-item nav-icon">
                    <a href="{% url "users:logout" %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

rdevelopment/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />



    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Bootstrap 4x -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.js"> </script>

    <style>
        .cont-opt-denuncia {
            width: 60%;
            margin-left: 20%;
            padding-left: 10%;
            margin-bottom: 20px;
        }

        .cont-btns {
            width: 10em;
            margin-left: 150px;
        }

        .s3 {
            text-align: center;
        }

        .cont-titulos {
            display: flex;
            justify-content: space-between;
        }

        .description-denun {
            text-align: justify;
        }

        .fiexd-btn-menu {
            /* transform: translate(0, 100%); */
            display: flex;
            margin-top: 9px;
            margin-bottom: -65px;
        }
    </style>

</head>
<body class="overflow: hidden;">

    {% include "nav.html" %}

    <div class="container mt-5">
        {% block container %}
        {% endblock%}
    </div>

</body>
</html>

rdevelopment/templates/nav.html
{% load static %}

    <div class="container">
        <div class="section">
            <div class="fiexd-btn-menu">
                <a class="btn-small sidenav-trigger" data-target="menu-side">
                    <i class="large material-icons">menu</i>
                </a>
            </div>

            <ul class="sidenav" id="menu-side">

                <li>
                    <div class="user-view">

                        <a href="{% url "users:detail" request.user.username %}">
                            {% if request.user.profile.picture %}
                                <img src="{{ request.user.profile.picture.url }}" alt="" class="circle"/>
                            {% else%}
                                <img src="{% static 'img/default-profile.png' %}" alt="" class="circle"/>
                            {% endif %}
                          </a>
                    </div>
                </li>

                <li>
                    <a href="{% url "users:detail" request.user.username %}">
                        <i class="material-icons">Profile</i> Perfil
                    </a>
                </li>

                <li>
                    <a href="{% url "posts:feed" %}">
                        <i class="material-icons">home</i> Inicio
                    </a>
                </li>

                <li>
                    <a href="{% url "posts:create" %}">
                        <i class="material-icons">public</i> Reporta!
                    </a>
                </li>

                <li>
                    <a href="#">
                        <i class="material-icons">add_comment</i> Pedagogía
                    </a>
                </li>
                <li>
                    <div class="divider"></div>
                </li>
                <li>
                    <a href="{% url "users:update" %}">
                        <i class="material-icons">settings</i> Editar cuenta
                    </a>
                </li>
                <li>
                    <a href="{% url "users:logout" %}">
                        <i class="material-icons">exit_to_app</i> Cerrar Sesion
                    </a>
                </li>
                <li>
                    <div class="divider"></div>
                </li>
                <li>
                    <a href="#">
                         Informacion
                    </a>
                </li>
                <li>
                    <a href="#">
                        Politica de privacidad
                    </a>
                </li>
                <li>
                    <a href="#">
                         Condiciones de uso
                    </a>
                </li>
            </ul>
        </div>
    </div>




    <!-- JavaScript Materialize css-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!-- JavaScrit bootstrap 4x  -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> -->


    <script>
        document.addEventListener('DOMContentLoaded', function() {

            var elems = document.querySelectorAll('.sidenav');
            var instances = M.Sidenav.init(elems);

            var elems = document.querySelectorAll('.slider');
            var instances = M.Slider.init(elems, {});

            var elems = document.querySelectorAll('.materialboxed');
            var instances = M.Materialbox.init(elems);

        });
    </script>
</nav>

rdevelopment/templates/pagination.html
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>

rdevelopment/templates/posts/_post_card.html
<div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
    <div class="media pt-3 pl-3 pb-1">
        <a href="{% url "users:detail" post.user.username %}">
            <img class="mr-3 rounded-circle" height="35" src="{{ post.profile.picture.url }}" alt="{{ post.user.get_full_name }}">
        </a>
        <div class="media-body">
            <p style="margin-top: 5px;">{{ post.user.get_full_name  }}</p>
        </div>
    </div>

    <img style="width: 100%;" src="{{ post.photo.url }}" alt="{{ post.title }}">

    <p class="mt-1 ml-2" >
        <a href="" style="color: #000; font-size: 20px;">
            <i class="far fa-heart"></i>
        </a> 30 likes
    </p>
    <p class="ml-2 mt-0 mb-2">
        <b>{{ post.title }}</b> - <small>{{ post.created }}</small>
    </p>
</div>

rdevelopment/templates/posts/feed.html
{% extends "base.html" %}

{% block head_content %}
    <title>SINGER</title>
{% endblock%}

{% block container %}
{% load static %}

<div class="cabezera">

        <div class="row">


            <div class="col s12">

                <div class="slider">
                    <ul class="slides">

                        <li>
                            <img src="{% static 'img/banner.jpg' %}" >

                        </li>

                        <li>
                            <img src="{% static 'img/banner2.jpg' %}">
                        </li>

                        <li>
                            <img src="{% static 'img/banner 3.jpg' %}">
                        </li>

                    </ul>
                </div>

            </div>

        </div>

    </div>

    <div class="container">
        <div class="row">
            {% for post in posts %}
                {% include "posts/post_card.html" %}
            {% endfor %}
        </div>
    </div>


    {% include "pagination.html" %}

{% endblock %}

rdevelopment/templates/posts/post_card.html
{% load static %}

<div class="center-block">
  <div class="row cont-titulos">
      <div class="col s3"><h2 class="text-left">{{ post.categories }}</h2></div>
      <div class="col s3"><h6 class="text-center"><a href="{% url "posts:detail" post.pk %}">{{ post.title }}</a></h6></div>
      <div class="col s3"><h3 class="text-right"><a href="{% url "users:detail" post.user.username %}">{{post.user.get_full_name}}</a></h3></div>
  </div>
  <div class="card mb-4 box-shadow">
    <img style="width: 100%;" src="{{ post.photo.url }}" alt="{{ post.title }}">
      <div class="card-body">
        <a href="#" style="color: #000; font-size: 20px;">
            <i class="far fa-hand-rock"></i>
        </a> 62 Personas apoyando
        <p class="card-text">{{ post.description }}</p>

        <p></p>
        <div>
        <h2>COMENTARIOS<h2>
        </div>
        <p>Esta increible esa idea, no crei que eso pasara en colombia</p>
        <textarea class="form-control counted" name="message" placeholder="Deje su comentario" rows="5" style="margin-bottom:10px;"></textarea>
        <button class="btn btn-info" type="submit">Comentar</button>
        <div class="d-flex justify-content-between align-items-center">
        <small class="text-muted">{{ post.city }}</small>
        <small class="text-muted">{{ post.created }}</small>

      </div>
    </div>
  </div>
  </div>
</div>

rdevelopment/templates/posts/search.html
{% extends "base.html" %}

{% block head_content %}
    <title>SINGER</title>
{% endblock%}

{% block container %}

    <div class="container">
        <div class="row">

          {% for post in posts %}


          {% endfor %}
        </div>
    </div>


    {% include "pagination.html" %}

{% endblock %}

rdevelopment/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %} {% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                <img src="{% static "img/singer.png" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>

</body>
</html>

rdevelopment/templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | SINGER </title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">

            <div class="col-sm-4 d-flex justify-content-center">
                <img
                    src="{{ user.profile.picture.url }}"
                    alt="@{{ user.username}}"
                    class="rounded-circle"
                    width="150px"
                    height="150px"
                />

            </div>

            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    {{ user.username }}
                    {% if user == request.user %}
                        <a
                            href="{% url "users:update" %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Edit profile
                        </a>
                    {% else %}
                        <a
                            href=""
                            class="ml-5 btn btn-sm btn-primary"
                        >
                            Follow
                        </a>
                    {% endif %}
                </h2>

                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ user.profile.posts_count }}785</b> posts
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.followers }}1,401</b> followers
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.following }}491</b> following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
                <a href="{% url "posts:detail" post.pk %}" class="border">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

rdevelopment/templates/users/login.html
{% extends "users/base.html" %}

{% load socialaccount %}

{% block head_content %}
<title>SINGER sign in</title>
{% endblock%}

{% block container %}

    {% if form.errors %}
        <p class="alert alert-danger">
            Your username and password didn't match. Please try again.
        </p>
    {% endif%}

    <form method="POST" action="{% url "users:login" %}">
        {% csrf_token %}

        <div class="form-group">
            <input class="form-control" type="text" placeholder="Username" name="username" />
        </div>

        <div class="form-group">
            <input class="form-control" type="password" placeholder="Password" name="password" />
        </div>


        <button class="btn btn-secondary btn-block mt-5" type="submit">Sign in!</button>
        <a class="btn btn-primary btn-block" href="#" method="oauth2" %}">
            <span class="fab fa-facebook"></span>
            Login with facebook
        </a>

    </form>

    <p class="mt-4">Don't have an account yet? <a href="{% url "users:signup" %}">Sign up here.</a></p>

{% endblock %}

rdevelopment/templates/users/signup.html
{% extends "users/base.html" %}

{% load socialaccount %}

{% block head_content %}
<title>SINGER sign up</title>
{% endblock %}

{% block container %}
   <div class="row justify-content-md-center">
      <div class="col-7 pt-2">
               <form action="{% url 'users:signup' %}" method="POST">
               {% csrf_token %}
                 <form method="POST" enctype="multipart/form-data">
                {{ form.as_p }}
        

                <button class="btn btn-secondary btn-block mt-5" type="submit">Register!</button
                     
         <a class="btn btn-primary btn-block" href="#"facebook" method="oauth2" %}">
            <span class="fab fa-facebook"></span>
                Signup with facebook
         </a>

      </div>
   </div>

{% endblock %}

rdevelopment/templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }} | Update profile</title>
{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            <form action="{% url 'users:update' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="media">
                    {% if profile.picture %}
                        <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" />
                    {% else%}
                        <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4"><input type="file" name="picture"></p>
                    </div>
                </div>

                {% for error in form.picture.errors %}
                <div class="alert alert-danger">
                    <b>Picture: </b>{{ error }}
                </div>
                {% endfor %}

                <hr><br>

                {# Website field #}
                <div class="form-group">
                    <label>Website</label>
                    <input
                        class="form-control {% if form.website.errors %}is-invalid{% endif %}"
                        type="text"
                        name="website"
                        placeholder="Website"
                        value="{% if form.errors %}{{ form.website.value }}{% else %}{{ profile.website }}{% endif %}"
                    />
                    <div class="invalid-feedback">
                        {% for error in form.website.errors %}
                            {{ error }}
                        {% endfor%}
                    </div>
                </div>

                {# Biography field #}
                <div class="form-group">
                    <label>Biography</label>
                    <textarea
                        class="form-control {% if form.biography.errors %}is-invalid{% endif %}"
                        name="biography"
                    >{% if form.errors %}{{ form.biography.value }}{% else %}{{ profile.biography }}{% endif %}</textarea>

                    <div class="invalid-feedback">
                        {% for error in form.biography.errors %}
                            {{ error }}
                        {% endfor%}
                    </div>
                </div>

                {# Phone number field #}
                <div class="form-group">
                    <label>Phone number</label>
                    <input
                        class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}"
                        type="text"
                        name="phone_number"
                        placeholder="Phone number"
                        value="{% if form.errors %}{{ form.phone_number.value }}{% else %}{{ profile.phone_number }}{% endif %}"
                    />
                    <div class="invalid-feedback">
                        {% for error in form.phone_number.errors %}
                            {{ error }}
                        {% endfor%}
                    </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}